# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Proyecto Computacion 2\computation-lab-2\Interfaces\UI\view_clasificar.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 714)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_reviews_to_classify = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_reviews_to_classify.setFont(font)
        self.tableWidget_reviews_to_classify.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_reviews_to_classify.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_reviews_to_classify.setObjectName("tableWidget_reviews_to_classify")
        self.tableWidget_reviews_to_classify.setColumnCount(5)
        self.tableWidget_reviews_to_classify.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews_to_classify.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews_to_classify.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews_to_classify.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews_to_classify.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews_to_classify.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget_reviews_to_classify, 1, 7, 1, 1)
        self.comboBox_algoritmo = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_algoritmo.setEnabled(True)
        self.comboBox_algoritmo.setObjectName("comboBox_algoritmo")
        self.comboBox_algoritmo.addItem("")
        self.gridLayout.addWidget(self.comboBox_algoritmo, 0, 7, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_filtro = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_filtro.setFont(font)
        self.label_filtro.setObjectName("label_filtro")
        self.horizontalLayout.addWidget(self.label_filtro)
        self.comboBox_filtro = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_filtro.setObjectName("comboBox_filtro")
        self.comboBox_filtro.addItem("")
        self.comboBox_filtro.addItem("")
        self.comboBox_filtro.addItem("")
        self.comboBox_filtro.addItem("")
        self.comboBox_filtro.addItem("")
        self.comboBox_filtro.addItem("")
        self.comboBox_filtro.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_filtro)
        self.lineEdit_filtro = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_filtro.setObjectName("lineEdit_filtro")
        self.horizontalLayout.addWidget(self.lineEdit_filtro)
        self.pushButton_applyfilter = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_applyfilter.setFont(font)
        self.pushButton_applyfilter.setObjectName("pushButton_applyfilter")
        self.horizontalLayout.addWidget(self.pushButton_applyfilter)
        self.pushButton_cleanfilter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cleanfilter.setObjectName("pushButton_cleanfilter")
        self.horizontalLayout.addWidget(self.pushButton_cleanfilter)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_Clasificar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Clasificar.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Clasificar.setFont(font)
        self.pushButton_Clasificar.setObjectName("pushButton_Clasificar")
        self.gridLayout.addWidget(self.pushButton_Clasificar, 2, 7, 1, 1)
        self.widget_resultados = QtWidgets.QWidget(self.centralwidget)
        self.widget_resultados.setObjectName("widget_resultados")
        self.gridLayout.addWidget(self.widget_resultados, 1, 8, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)
        self.pushButton_addall = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_addall.setFont(font)
        self.pushButton_addall.setObjectName("pushButton_addall")
        self.verticalLayout.addWidget(self.pushButton_addall)
        self.pushButton_remove = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.verticalLayout.addWidget(self.pushButton_remove)
        self.pushButton_removeall = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_removeall.setFont(font)
        self.pushButton_removeall.setObjectName("pushButton_removeall")
        self.verticalLayout.addWidget(self.pushButton_removeall)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.tableWidget_reviews = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_reviews.setFont(font)
        self.tableWidget_reviews.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_reviews.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_reviews.setObjectName("tableWidget_reviews")
        self.tableWidget_reviews.setColumnCount(4)
        self.tableWidget_reviews.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_reviews.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget_reviews, 1, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_toCSV = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_toCSV.setEnabled(False)
        self.pushButton_toCSV.setObjectName("pushButton_toCSV")
        self.horizontalLayout_2.addWidget(self.pushButton_toCSV)
        self.pushButton_guardar_resultados = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_guardar_resultados.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_guardar_resultados.setFont(font)
        self.pushButton_guardar_resultados.setObjectName("pushButton_guardar_resultados")
        self.horizontalLayout_2.addWidget(self.pushButton_guardar_resultados)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 7, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clasificacion"))
        item = self.tableWidget_reviews_to_classify.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_reviews_to_classify.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etiqueta"))
        item = self.tableWidget_reviews_to_classify.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Etiqueta pred"))
        item = self.tableWidget_reviews_to_classify.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nombre Fichero"))
        item = self.tableWidget_reviews_to_classify.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Texto"))
        self.comboBox_algoritmo.setItemText(0, _translate("MainWindow", "Selecciona modelo"))
        self.label_filtro.setText(_translate("MainWindow", "Filtro"))
        self.comboBox_filtro.setItemText(0, _translate("MainWindow", "contiene"))
        self.comboBox_filtro.setItemText(1, _translate("MainWindow", "no contiene"))
        self.comboBox_filtro.setItemText(2, _translate("MainWindow", "acaba en"))
        self.comboBox_filtro.setItemText(3, _translate("MainWindow", "no acaba en"))
        self.comboBox_filtro.setItemText(4, _translate("MainWindow", "coinciden minMAYUS"))
        self.comboBox_filtro.setItemText(5, _translate("MainWindow", "coincide exacto"))
        self.comboBox_filtro.setItemText(6, _translate("MainWindow", "empieza por"))
        self.pushButton_applyfilter.setText(_translate("MainWindow", "Aplicar filtro"))
        self.pushButton_cleanfilter.setText(_translate("MainWindow", "Limpiar filtro"))
        self.pushButton_Clasificar.setText(_translate("MainWindow", "Clasificar"))
        self.pushButton_back.setText(_translate("MainWindow", "Atrás"))
        self.pushButton_add.setText(_translate("MainWindow", "Añadir"))
        self.pushButton_addall.setText(_translate("MainWindow", "Añadir todas"))
        self.pushButton_remove.setText(_translate("MainWindow", "Eliminar"))
        self.pushButton_removeall.setText(_translate("MainWindow", "Eliminar todas"))
        item = self.tableWidget_reviews.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_reviews.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etiqueta"))
        item = self.tableWidget_reviews.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nombre Fichero"))
        item = self.tableWidget_reviews.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Texto"))
        self.pushButton_toCSV.setText(_translate("MainWindow", "Exportar a CSV"))
        self.pushButton_guardar_resultados.setText(_translate("MainWindow", "Guardar resultados"))

