# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_ventana_superusuario.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.tableWidget, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_Registrar_usuario = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Registrar_usuario.setFont(font)
        self.pushButton_Registrar_usuario.setObjectName("pushButton_Registrar_usuario")
        self.gridLayout_4.addWidget(self.pushButton_Registrar_usuario, 0, 0, 1, 1)
        self.pushButton_Eliminar_usuario = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Eliminar_usuario.setFont(font)
        self.pushButton_Eliminar_usuario.setObjectName("pushButton_Eliminar_usuario")
        self.gridLayout_4.addWidget(self.pushButton_Eliminar_usuario, 0, 2, 1, 1)
        self.pushButton_Modificar_usuario = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Modificar_usuario.setFont(font)
        self.pushButton_Modificar_usuario.setObjectName("pushButton_Modificar_usuario")
        self.gridLayout_4.addWidget(self.pushButton_Modificar_usuario, 0, 1, 1, 1)
        self.pushButton_Atras = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Atras.setFont(font)
        self.pushButton_Atras.setObjectName("pushButton_Atras")
        self.gridLayout_4.addWidget(self.pushButton_Atras, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_Poryectos = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_Poryectos.setFont(font)
        self.tableWidget_Poryectos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Poryectos.setObjectName("tableWidget_Poryectos")
        self.tableWidget_Poryectos.setColumnCount(2)
        self.tableWidget_Poryectos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Poryectos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Poryectos.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tableWidget_Poryectos, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Panel de administracion de usuarios"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Role"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actividad"))
        self.pushButton_Registrar_usuario.setText(_translate("MainWindow", "Registrar usuario"))
        self.pushButton_Eliminar_usuario.setText(_translate("MainWindow", "Eliminar/Activar usuario"))
        self.pushButton_Modificar_usuario.setText(_translate("MainWindow", "Modificar usuario"))
        self.pushButton_Atras.setText(_translate("MainWindow", "Atras"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Usuarios"))
        item = self.tableWidget_Poryectos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Usuario"))
        item = self.tableWidget_Poryectos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Proyecto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Proyectos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

