# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Proyecto Computacion 2\computation-lab-2\Interfaces\UI\view_ventana_superusuario.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_Registrar_usuario = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Registrar_usuario.setFont(font)
        self.pushButton_Registrar_usuario.setObjectName("pushButton_Registrar_usuario")
        self.gridLayout_4.addWidget(self.pushButton_Registrar_usuario, 0, 0, 1, 1)
        self.pushButton_Eliminar_usuario = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Eliminar_usuario.setFont(font)
        self.pushButton_Eliminar_usuario.setObjectName("pushButton_Eliminar_usuario")
        self.gridLayout_4.addWidget(self.pushButton_Eliminar_usuario, 0, 2, 1, 1)
        self.pushButton_Modificar_usuario = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Modificar_usuario.setFont(font)
        self.pushButton_Modificar_usuario.setObjectName("pushButton_Modificar_usuario")
        self.gridLayout_4.addWidget(self.pushButton_Modificar_usuario, 0, 1, 1, 1)
        self.pushButton_Atras = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Atras.setFont(font)
        self.pushButton_Atras.setObjectName("pushButton_Atras")
        self.gridLayout_4.addWidget(self.pushButton_Atras, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 2, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(650, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.tableWidget_Poryectos = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Poryectos.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_Poryectos.setFont(font)
        self.tableWidget_Poryectos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Poryectos.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_Poryectos.setObjectName("tableWidget_Poryectos")
        self.tableWidget_Poryectos.setColumnCount(1)
        self.tableWidget_Poryectos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Poryectos.setHorizontalHeaderItem(0, item)
        self.gridLayout.addWidget(self.tableWidget_Poryectos, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Panel de administracion de usuarios"))
        self.pushButton_Registrar_usuario.setText(_translate("MainWindow", "Registrar usuario"))
        self.pushButton_Eliminar_usuario.setText(_translate("MainWindow", "Eliminar/Activar usuario"))
        self.pushButton_Modificar_usuario.setText(_translate("MainWindow", "Modificar usuario"))
        self.pushButton_Atras.setText(_translate("MainWindow", "Atras"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Role"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Actividad"))
        item = self.tableWidget_Poryectos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Proyectos Asociados"))

