# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Proyecto Computacion 2\computation-lab-2\Interfaces\UI\view_load_files.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 704)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.file_tab)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.file_tableWidget = QtWidgets.QTableWidget(self.file_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.file_tableWidget.setFont(font)
        self.file_tableWidget.setObjectName("file_tableWidget")
        self.file_tableWidget.setColumnCount(3)
        self.file_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.file_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.file_tableWidget, 0, 0, 1, 3)
        self.comboBox_labels_file = QtWidgets.QComboBox(self.file_tab)
        self.comboBox_labels_file.setObjectName("comboBox_labels_file")
        self.comboBox_labels_file.addItem("")
        self.comboBox_labels_file.addItem("")
        self.comboBox_labels_file.addItem("")
        self.comboBox_labels_file.addItem("")
        self.comboBox_labels_file.addItem("")
        self.gridLayout.addWidget(self.comboBox_labels_file, 1, 1, 1, 1)
        self.file_pushButton_add = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_add.setObjectName("file_pushButton_add")
        self.gridLayout.addWidget(self.file_pushButton_add, 1, 2, 1, 1)
        self.file_lineEditPath = QtWidgets.QLineEdit(self.file_tab)
        self.file_lineEditPath.setEnabled(True)
        self.file_lineEditPath.setInputMask("")
        self.file_lineEditPath.setText("")
        self.file_lineEditPath.setReadOnly(True)
        self.file_lineEditPath.setObjectName("file_lineEditPath")
        self.gridLayout.addWidget(self.file_lineEditPath, 2, 0, 1, 3)
        self.pushButton_back = QtWidgets.QPushButton(self.file_tab)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 3, 0, 2, 1)
        self.file_pushButton_selectfolder = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_selectfolder.setObjectName("file_pushButton_selectfolder")
        self.gridLayout.addWidget(self.file_pushButton_selectfolder, 3, 1, 1, 2)
        self.file_pushButton_clear = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_clear.setObjectName("file_pushButton_clear")
        self.gridLayout.addWidget(self.file_pushButton_clear, 4, 1, 1, 1)
        self.file_pushButton_load = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_load.setEnabled(False)
        self.file_pushButton_load.setObjectName("file_pushButton_load")
        self.gridLayout.addWidget(self.file_pushButton_load, 4, 2, 1, 1)
        self.tabWidget.addTab(self.file_tab, "")
        self.URL_tab = QtWidgets.QWidget()
        self.URL_tab.setObjectName("URL_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.URL_tab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.URL_review_tableWidget = QtWidgets.QTableWidget(self.URL_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.URL_review_tableWidget.setFont(font)
        self.URL_review_tableWidget.setObjectName("URL_review_tableWidget")
        self.URL_review_tableWidget.setColumnCount(3)
        self.URL_review_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.URL_review_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.URL_review_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.URL_review_tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.URL_review_tableWidget, 1, 2, 1, 1)
        self.URL_pushButton_clear = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_clear.setObjectName("URL_pushButton_clear")
        self.gridLayout_2.addWidget(self.URL_pushButton_clear, 6, 2, 1, 1)
        self.URL_pushButton_back = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_back.setObjectName("URL_pushButton_back")
        self.gridLayout_2.addWidget(self.URL_pushButton_back, 6, 1, 1, 1)
        self.URL_pushButton_selectfolder = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_selectfolder.setObjectName("URL_pushButton_selectfolder")
        self.gridLayout_2.addWidget(self.URL_pushButton_selectfolder, 4, 1, 1, 1)
        self.URL_pushButton_load = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_load.setEnabled(False)
        self.URL_pushButton_load.setObjectName("URL_pushButton_load")
        self.gridLayout_2.addWidget(self.URL_pushButton_load, 4, 2, 1, 1)
        self.lineEdit_URL = QtWidgets.QLineEdit(self.URL_tab)
        self.lineEdit_URL.setReadOnly(False)
        self.lineEdit_URL.setObjectName("lineEdit_URL")
        self.gridLayout_2.addWidget(self.lineEdit_URL, 2, 1, 1, 1)
        self.URL_pushButton_add = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_add.setObjectName("URL_pushButton_add")
        self.gridLayout_2.addWidget(self.URL_pushButton_add, 3, 1, 1, 1)
        self.label_URL = QtWidgets.QLabel(self.URL_tab)
        self.label_URL.setObjectName("label_URL")
        self.gridLayout_2.addWidget(self.label_URL, 2, 0, 1, 1)
        self.URL_tableWidget = QtWidgets.QTableWidget(self.URL_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.URL_tableWidget.setFont(font)
        self.URL_tableWidget.setObjectName("URL_tableWidget")
        self.URL_tableWidget.setColumnCount(1)
        self.URL_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.URL_tableWidget.setHorizontalHeaderItem(0, item)
        self.gridLayout_2.addWidget(self.URL_tableWidget, 1, 1, 1, 1)
        self.URL_pushButton_processURLs = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_processURLs.setEnabled(False)
        self.URL_pushButton_processURLs.setObjectName("URL_pushButton_processURLs")
        self.gridLayout_2.addWidget(self.URL_pushButton_processURLs, 3, 2, 1, 1)
        self.URL_comboBox_labels = QtWidgets.QComboBox(self.URL_tab)
        self.URL_comboBox_labels.setObjectName("URL_comboBox_labels")
        self.URL_comboBox_labels.addItem("")
        self.URL_comboBox_labels.addItem("")
        self.gridLayout_2.addWidget(self.URL_comboBox_labels, 2, 2, 1, 1)
        self.tabWidget.addTab(self.URL_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1051, 31))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cargar Opiniones"))
        item = self.file_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.file_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etiqueta"))
        item = self.file_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ruta"))
        self.comboBox_labels_file.setItemText(0, _translate("MainWindow", "Seleccionar etiqueta"))
        self.comboBox_labels_file.setItemText(1, _translate("MainWindow", "Unlabeled"))
        self.comboBox_labels_file.setItemText(2, _translate("MainWindow", "etiqueta1"))
        self.comboBox_labels_file.setItemText(3, _translate("MainWindow", "etiqueta2"))
        self.comboBox_labels_file.setItemText(4, _translate("MainWindow", "mimammamemimma"))
        self.file_pushButton_add.setText(_translate("MainWindow", "Agregar"))
        self.pushButton_back.setText(_translate("MainWindow", "Atrás"))
        self.file_pushButton_selectfolder.setText(_translate("MainWindow", "Seleccionar carpeta"))
        self.file_pushButton_clear.setText(_translate("MainWindow", "Borrar"))
        self.file_pushButton_load.setText(_translate("MainWindow", "Cargar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.file_tab), _translate("MainWindow", "Fichero"))
        item = self.URL_review_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "URL"))
        item = self.URL_review_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etiqueta"))
        item = self.URL_review_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Opinion"))
        self.URL_pushButton_clear.setText(_translate("MainWindow", "Borrar"))
        self.URL_pushButton_back.setText(_translate("MainWindow", "Atrás"))
        self.URL_pushButton_selectfolder.setText(_translate("MainWindow", "Seleccionar fichero URLs"))
        self.URL_pushButton_load.setText(_translate("MainWindow", "Cargar"))
        self.URL_pushButton_add.setText(_translate("MainWindow", "Agregar"))
        self.label_URL.setText(_translate("MainWindow", "URL"))
        item = self.URL_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "URL"))
        self.URL_pushButton_processURLs.setText(_translate("MainWindow", "Procesar URLs"))
        self.URL_comboBox_labels.setItemText(0, _translate("MainWindow", "Seleccionar etiqueta"))
        self.URL_comboBox_labels.setItemText(1, _translate("MainWindow", "Unlabeled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.URL_tab), _translate("MainWindow", "URL"))
