# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Proyecto Computacion 2\computation-lab-2\Interfaces\view_load_files.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 704)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 1031, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.file_tableWidget = QtWidgets.QTableWidget(self.file_tab)
        self.file_tableWidget.setGeometry(QtCore.QRect(15, 31, 1001, 381))
        self.file_tableWidget.setObjectName("file_tableWidget")
        self.file_tableWidget.setColumnCount(0)
        self.file_tableWidget.setRowCount(0)
        self.file_pushButton_add = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_add.setGeometry(QtCore.QRect(900, 420, 114, 32))
        self.file_pushButton_add.setObjectName("file_pushButton_add")
        self.file_pushButton_load = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_load.setGeometry(QtCore.QRect(900, 560, 114, 32))
        self.file_pushButton_load.setObjectName("file_pushButton_load")
        self.file_pushButton_clear = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_clear.setGeometry(QtCore.QRect(780, 560, 114, 32))
        self.file_pushButton_clear.setObjectName("file_pushButton_clear")
        self.file_pushButton_selectfolder = QtWidgets.QPushButton(self.file_tab)
        self.file_pushButton_selectfolder.setGeometry(QtCore.QRect(783, 520, 231, 32))
        self.file_pushButton_selectfolder.setObjectName("file_pushButton_selectfolder")
        self.file_textEdit_path = QtWidgets.QTextEdit(self.file_tab)
        self.file_textEdit_path.setGeometry(QtCore.QRect(20, 480, 991, 31))
        self.file_textEdit_path.setObjectName("file_textEdit_path")
        self.comboBox_labels_file = QtWidgets.QComboBox(self.file_tab)
        self.comboBox_labels_file.setGeometry(QtCore.QRect(700, 420, 191, 32))
        self.comboBox_labels_file.setObjectName("comboBox_labels_file")
        self.comboBox_labels_file.addItem("")
        self.comboBox_labels_file.addItem("")
        self.comboBox_labels_file.addItem("")
        self.comboBox_labels_file.addItem("")
        self.pushButton_back = QtWidgets.QPushButton(self.file_tab)
        self.pushButton_back.setGeometry(QtCore.QRect(30, 560, 81, 31))
        self.pushButton_back.setObjectName("pushButton_back")
        self.tabWidget.addTab(self.file_tab, "")
        self.URL_tab = QtWidgets.QWidget()
        self.URL_tab.setObjectName("URL_tab")
        self.URL_tableWidget = QtWidgets.QTableWidget(self.URL_tab)
        self.URL_tableWidget.setGeometry(QtCore.QRect(15, 31, 1001, 381))
        self.URL_tableWidget.setObjectName("URL_tableWidget")
        self.URL_tableWidget.setColumnCount(3)
        self.URL_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.URL_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.URL_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.URL_tableWidget.setHorizontalHeaderItem(2, item)
        self.URL_pushButton_add = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_add.setGeometry(QtCore.QRect(900, 420, 111, 32))
        self.URL_pushButton_add.setObjectName("URL_pushButton_add")
        self.URL_pushButton_load = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_load.setGeometry(QtCore.QRect(900, 560, 111, 32))
        self.URL_pushButton_load.setObjectName("URL_pushButton_load")
        self.URL_pushButton_clear = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_clear.setGeometry(QtCore.QRect(780, 560, 111, 32))
        self.URL_pushButton_clear.setObjectName("URL_pushButton_clear")
        self.URL_pushButton_selectfolder = QtWidgets.QPushButton(self.URL_tab)
        self.URL_pushButton_selectfolder.setGeometry(QtCore.QRect(780, 520, 231, 32))
        self.URL_pushButton_selectfolder.setObjectName("URL_pushButton_selectfolder")
        self.URL_textEdit_path = QtWidgets.QTextEdit(self.URL_tab)
        self.URL_textEdit_path.setGeometry(QtCore.QRect(20, 479, 981, 31))
        self.URL_textEdit_path.setObjectName("URL_textEdit_path")
        self.tabWidget.addTab(self.URL_tab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1051, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cargar Opiniones"))
        self.file_pushButton_add.setText(_translate("MainWindow", "Agregar"))
        self.file_pushButton_load.setText(_translate("MainWindow", "Cargar"))
        self.file_pushButton_clear.setText(_translate("MainWindow", "Borrar"))
        self.file_pushButton_selectfolder.setText(_translate("MainWindow", "Seleccionar carpeta"))
        self.comboBox_labels_file.setItemText(0, _translate("MainWindow", "etiquetas"))
        self.comboBox_labels_file.setItemText(1, _translate("MainWindow", "etiqueta1"))
        self.comboBox_labels_file.setItemText(2, _translate("MainWindow", "etiqueta2"))
        self.comboBox_labels_file.setItemText(3, _translate("MainWindow", "mimammamemimma"))
        self.pushButton_back.setText(_translate("MainWindow", "Atrás"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.file_tab), _translate("MainWindow", "Fichero"))
        item = self.URL_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.URL_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Creado"))
        item = self.URL_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fecha de Creacion"))
        self.URL_pushButton_add.setText(_translate("MainWindow", "Agregar"))
        self.URL_pushButton_load.setText(_translate("MainWindow", "Cargar"))
        self.URL_pushButton_clear.setText(_translate("MainWindow", "Borrar"))
        self.URL_pushButton_selectfolder.setText(_translate("MainWindow", "Seleccionar carpeta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.URL_tab), _translate("MainWindow", "URL"))
